// what user sees -> what NSE API needs
export const NSE_INDEX_MAP: Record<string, string> = {
  "Nifty 50": "NIFTY 50",
  "Nifty Next 50": "NIFTY NEXT 50",
  "Nifty Bank": "NIFTY BANK",
  "Nifty Financial Services": "NIFTY FINANCIAL SERVICES",
  "Nifty IT": "NIFTY IT",
  "Nifty FMCG": "NIFTY FMCG",
  "Nifty Auto": "NIFTY AUTO",
  "Nifty Pharma": "NIFTY PHARMA",
  "Nifty Metal": "NIFTY METAL",
  "Nifty PSU Bank": "NIFTY PSU BANK",
  "Nifty Realty": "NIFTY REALTY",
  "Nifty Energy": "NIFTY ENERGY",
  "Nifty Media": "NIFTY MEDIA",
  "Nifty Commodities": "NIFTY COMMODITIES",
  "Nifty Infrastructure": "NIFTY INFRASTRUCTURE",
  "Nifty Consumption": "NIFTY CONSUMPTION",
  "Nifty CPSE": "NIFTY CPSE",
  "Nifty PSE": "NIFTY PSE",
  "Nifty Healthcare": "NIFTY HEALTHCARE INDEX",
  "Nifty Private Bank": "NIFTY PRIVATE BANK",
  "Capital Goods": "NIFTY CAPITAL MKT",
  "Automobile and Auto Components": "NIFTY AUTO",
  Chemicals: "NIFTY CHEMICALS",
  Construction: "NIFTY INFRA",
  "Consumer Durables": "NIFTY CONSR DURBL",
  "Fast Moving Consumer Goods": "NIFTY FMCG",
  "Financial Services": "NIFTY FIN SERVICE",
  Healthcare: "NIFTY HEALTHCARE",
  "Information Technology": "NIFTY IT",
  "Media, Entertainment & Publication": "NIFTY MEDIA",
  "Metals & Mining": "NIFTY METAL",
  "Oil, Gas & Consumable Fuels": "NIFTY OIL AND GAS",
  Power: "NIFTY ENERGY",
  Realty: "NIFTY REALTY",
  // "Telecommunication": "",
  // "Textiles": "",
  // "Utilities": ""
};
