import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { TooltipProvider } from "@/components/ui/tooltip";
import Providers from "./providers/provider";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const color = cookieStore.get("theme")?.value ?? "blue";
  const mode = cookieStore.get("mode")?.value ?? "light";
  const radius = cookieStore.get("theme-radius")?.value ?? "rounded";
  const themeClass = mode === "dark" ? `theme-${color}-dark` : `theme-${color}`;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${themeClass} ${radius === "rounded" ? "radius-rounded" : "radius-square"}`}
    >
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
